# Variebles
@baseUrl = http://localhost:3333
@token = eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zQlhDVHlhaGZuQ1EyNmxHcFNQbWU5ZzZVZVIiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Nzg1MDgzOTgsImZ2YSI6WzcxMDksLTFdLCJpYXQiOjE3Nzg1MDgzMzgsImlzcyI6Imh0dHBzOi8vZ2FtZS1iZWFnbGUtOTUuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzc4NTA4MzI4LCJzaWQiOiJzZXNzXzNETUFzMXdGdW1paDBHcDk5dndBZmJrd0F1RSIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfM0NQTlFpc1YwbzVmRnJwR1FPc0NZNmdKb2hGIiwidiI6Mn0.hiauh1yb1fQDPBMSP_rJP72xxl-9kO9VBEmYCDYRkciSzzXLkiRl2e7XFFPL0q7uchDEMDr_7kxJETW_XObt5rgd2GFCdKaSRIprBpHYUx5qoZ29oS7CuWAEqwmP3phOtafamMxGLEXZDtV_H8cIMpuNV-xwHkqnkEHgpx-Svsi9RCqMXjvbaxXJk6380K2eTt3TVt1QXutyFab7Mah4Tdy_h7UZ6dnUPc6dFiRoezHA8dnC8CYhu6pT5Qy1oG6007j3uf--fnu-zGkQPO-IhHBwMSEfdGvWpBiGOp2gIQL19FUo0XtNvvJ-zzG0972oCagQarceqKEplBhDQG6CNQ
# Get UserId Token
GET {{baseUrl}}/me
Authorization: Bearer {{token}}

###

# Get Form by Token
GET {{baseUrl}}/forms
Authorization: Bearer {{token}}

###
# Post Pre Diagnostics by Token
POST {{baseUrl}}/pre-diagnostics
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "formId": "1ee91a6a-a0a0-437d-aee4-139b233c699a",
    "model": "gemini-3-flash-preview"
}

###

# Get Pre Diagnostics by Token
GET {{baseUrl}}/pre-diagnostics
Authorization: Bearer {{token}}