# Variebles
@baseUrl = http://localhost:3333
@token = eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zQlhDVHlhaGZuQ1EyNmxHcFNQbWU5ZzZVZVIiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Nzg1NDkxNjUsImZ2YSI6Wzc3ODgsLTFdLCJpYXQiOjE3Nzg1NDkxMDUsImlzcyI6Imh0dHBzOi8vZ2FtZS1iZWFnbGUtOTUuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzc4NTQ5MDk1LCJzaWQiOiJzZXNzXzNETUFzMXdGdW1paDBHcDk5dndBZmJrd0F1RSIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfM0NQTlFpc1YwbzVmRnJwR1FPc0NZNmdKb2hGIiwidiI6Mn0.hh8ZnpIJRB3gkEXHh6MF1wK0mTxTNtS5Jl5jpwi7_HglYryxpSMvjqfMwuwHBrJuoZuBtydoxeol7zCllqmV3pQyOnxw7N1Ab9F0xpgxYfyER6N35uHblIeKGG_Jgkto59YDIKaqvjcmg7Pk1g3cp6_4nx9ivm4J6DHTf0TREbd6N-DLoMAtn1lLcU9sjf7woHyjPlZnXDZ-2SmeKz3xk7MD5bOF2AK0U_Ey8_bVWhZBzm07u52-uDwdhZKLGFtBSh5D5ZvRMct0aLRiEq6Sk1zX46yS-KrsaMUGf18Ro60k0F2CtvkkmLdkm528_iZy1KZWEDw0AcyCuuA8HD436A

###

# Get Form by Token
GET {{baseUrl}}/forms
Authorization: Bearer {{token}}

###
# Post Pre Diagnostics by Token
POST {{baseUrl}}/pre-diagnostics
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "formId": "1eb61e5d-3d43-4b17-b117-7b02d47fed0e",
    "model": "gemini-3-flash-preview"
}

###

# Get Pre Diagnostics by Token
GET {{baseUrl}}/pre-diagnostics
Authorization: Bearer {{token}}