# Variebles
@baseUrl = http://localhost:3333
@token = eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zQlhDVHlhaGZuQ1EyNmxHcFNQbWU5ZzZVZVIiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3NzgzNTkwMjQsImZ2YSI6WzQ2MTksLTFdLCJpYXQiOjE3NzgzNTg5NjQsImlzcyI6Imh0dHBzOi8vZ2FtZS1iZWFnbGUtOTUuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzc4MzU4OTU0LCJzaWQiOiJzZXNzXzNETUFzMXdGdW1paDBHcDk5dndBZmJrd0F1RSIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfM0NQTlFpc1YwbzVmRnJwR1FPc0NZNmdKb2hGIiwidiI6Mn0.Wfo8_sBgF7UDzbehuLrgItezjwYdzTDcLUEuzwhCxlmuh0Do-KAqBlVnL8Nij9v5FUCUQ5nwXSmo3jsul-HtX3fuXVqXlL48lT4KyKJx2jmWS8Qm-1CXSqePP5mlKW3RtH_bbe-qBIySxRgxvb_pWd2PsCYEcqtZhMK5zzfKivnDPp9H_ZUgKHFmKFixQPZZk92g0Oq7jmLmnfYkI7uxeICqG8cGF41zNVSYLys5B6QtZk-QrPjo3FYZsi__rOEtJxbeAekeRIams4zfJ3rACxIp1DKsjRdoWe5zJt8Z6ozTuyxM2q3L7EpBbidOm-rVUwVQJuCbpKb2bvsLt5Fv9Q
# Get UserId Token
GET {{baseUrl}}/me
Authorization: Bearer {{token}}

###

# Get Form by Token
GET {{baseUrl}}/forms
Authorization: Bearer {{token}}

###
# Post Pre Diagnostics by Token
POST {{baseUrl}}/pre-diagnostics
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "formId": "1ee91a6a-a0a0-437d-aee4-139b233c699a",
    "model": "gemini-3-flash-preview"
}

###

# Get Pre Diagnostics by Token
GET {{baseUrl}}/pre-diagnostics
Authorization: Bearer {{token}}